/**
 * Learner-facing copy for each placeholder sign. IDs must match
 * public/data/signs/manifest.json (generated by
 * scripts/generate-placeholder-signs.mjs).
 *
 * These are synthetic demo gestures, not verified Auslan vocabulary — see
 * PlaceholderNotice / README. Replace this content once real, Auslan-fluent-
 * signer-checked signs are available.
 */
export interface SignInfo {
  id: string;
  label: string;
  category: string;
  description: string;
  steps: string[];
}

export const SIGN_INFO: Record<string, SignInfo> = {
  "demo-sign-a": {
    id: "demo-sign-a",
    label: "Demo Sign A",
    category: "Placeholder demo",
    description: "A one-handed gesture that opens into a flat hand, then closes into a fist, then opens again.",
    steps: [
      "Hold your right hand up, fingers open and relaxed.",
      "Slowly close your fingers into a loose fist.",
      "Open your hand back out to the starting position.",
    ],
  },
  "demo-sign-b": {
    id: "demo-sign-b",
    label: "Demo Sign B",
    category: "Placeholder demo",
    description: "An open hand that waves smoothly from side to side.",
    steps: [
      "Hold your right hand up with fingers spread.",
      "Move your hand to the left, then to the right, in one smooth motion.",
      "Repeat the side-to-side motion twice.",
    ],
  },
  "demo-sign-c": {
    id: "demo-sign-c",
    label: "Demo Sign C",
    category: "Placeholder demo",
    description: "An extended index finger, held steady, with the other fingers curled in.",
    steps: [
      "Curl your thumb, middle, ring and pinky fingers into your palm.",
      "Extend your index finger straight up.",
      "Hold the position steady for a moment.",
    ],
  },
  "demo-sign-d": {
    id: "demo-sign-d",
    label: "Demo Sign D",
    category: "Placeholder demo",
    description: "Both hands raised and waving gently together.",
    steps: [
      "Raise both hands to shoulder height, palms facing out.",
      "Gently wave both hands side to side, mirroring each other.",
    ],
  },
};

export function getSignInfo(id: string): SignInfo | undefined {
  return SIGN_INFO[id];
}
