/**
 * Stick Figure Word Bank - Scene Classification (i3), Level-2 Breakdown Edition
 * Total words: 3,215  |  Level-1 scenes: 34 categories  |  Level-2 sub-scenes: 113 categories
 * Classification: A = Everyday Scenes  |  B = Specialised Domains  |  C = Grammar Words / Abstract Concepts
 */

export type ScenarioCategory = 'A' | 'B' | 'C';

export interface SubScenario {
  id: string;
  name: string;
  wordCount: number;
  words: string[];
}

export interface ScenarioGroup {
  id: string;
  category: ScenarioCategory;
  categoryName: string;
  title: string;
  icon: string;
  wordCount: number;
  subScenarios: SubScenario[];
}

export const SCENARIO_CATEGORIES: ScenarioGroup[] = [
  {
    id: 'A01',
    category: 'A',
    categoryName: 'Everyday Scenes',
    title: 'Café / Restaurant / Ordering',
    icon: '🍷',
    wordCount: 41,
    subScenarios: [
      {
        id: 'A01-1',
        name: 'Drinks',
        wordCount: 17,
        words: ["ALCOHOL", "BEER", "BEVERAGE", "CAPPUCCINO", "CHAMPAGNE", "COCKTAIL", 
          "COFFEE BEANS", "COLA", "CORDIAL", "JUICE", "LEMONADE", "MILKSHAKE", "ORANGE JUICE", 
          "TEA", "TEA BAG", "WHISKY", "WINE"],
      },
      {
        id: 'A01-2',
        name: 'Meals',
        wordCount: 7,
        words: ["BANQUET", "BURGER", "CROISSANT", "FEAST", "LUNCH", "PIZZA", "SCONES"],
      },
      {
        id: 'A01-3',
        name: 'Ordering / Service / Venues',
        wordCount: 6,
        words: ["BARMAN", "BARTENDER", "BILL", "CAFE", "RESTAURANT", "WAITER"],
      },
      {
        id: 'A01-4',
        name: 'Tableware / Dining Actions',
        wordCount: 11,
        words: ["CORK", "DRIPOLATOR", "FINISH (DRINK)", "FULL (SATED)", "GLASS (CUP)", "IMBIBE", 
          "MUG", "SATED", "STRAW", "TEASPOON"],
      },
    ],
  },
  {
    id: 'A02',
    category: 'A',
    categoryName: 'Everyday Scenes',
    title: 'Supermarket / Shopping / Payment',
    icon: '🛒',
    wordCount: 34,
    subScenarios: [
      {
        id: 'A02-1',
        name: 'Shops / Goods',
        wordCount: 12,
        words: ["ADVERTISEMENT", "AUCTION", "DELIVERY", "LABEL", "NEWSAGENT", "PACKET", "SALE", 
          "SHOP", "SUPPLY", "TRADE", "TRADE IN"],
      },
      {
        id: 'A02-2',
        name: 'Payment / Price',
        wordCount: 17,
        words: ["AFFORD", "BID (AUCTION)", "BID (BET)", "CASH REGISTER", "CHARGE", "CHEAP", 
          "CREDIT CARD", "FREE (WITHOUT COST)", "INEXPENSIVE", "PAY", "PAY CASH", "PAY FOR", 
          "PRICE", "PURCHASE", "SWIPE", "TAP AND PAY", "WORTH"],
      },
      {
        id: 'A02-3',
        name: 'Shopping Actions / Equipment',
        wordCount: 5,
        words: ["BAG", "BASKET", "BOX", "CART", "LINE UP"],
      },
    ],
  },
  {
    id: 'A03',
    category: 'A',
    categoryName: 'Everyday Scenes',
    title: 'Kitchen / Cooking / Ingredients',
    icon: '👨‍🍳',
    wordCount: 134,
    subScenarios: [
      {
        id: 'A03-1',
        name: 'Fruit & Vegetables',
        wordCount: 30,
        words: ["APPLE", "APRICOT", "BANANA", "BEANS", "BERRY", "CABBAGE", "CHERRY", "CHILLI", 
          "CORN COB", "FRUIT", "GARLIC", "GRAPEFRUIT", "GRAPES", "LEMON", "LETTUCE", "MELON", 
          "MUSHROOM", "NUT", "ONION", "ORANGE", "PARSNIP", "PEACH", "PEAR", "PINEAPPLE", "PLUM", 
          "POTATO", "PUMPKIN", "STRAWBERRY", "TOMATO", "VEGETABLES"],
      },
      {
        id: 'A03-2',
        name: 'Meat, Eggs & Dairy / Staples',
        wordCount: 20,
        words: ["BACON", "BREAD", "BUTTER", "CHEESE", "CREAM", "HAM", "HARD-BOILED EGG", "MILK", 
          "MINCE", "MUTTON", "OYSTER", "PRAWN", "RICE", "SAUSAGE", "SCRAMBLED EGGS", "SPAGHETTI", 
          "TOAST", "TRIPE", "VEGEMITE", "VEGETARIAN"],
      },
      {
        id: 'A03-3',
        name: 'Seasonings / Snacks & Desserts',
        wordCount: 33,
        words: ["CAKE", "CHEWING GUM", "CHIP", "CHOCOLATE", "COOKIE", "CRACKER", "CRUMBS", "DIP", 
          "DOUGH", "FLOUR", "GRAVY", "HONEY", "ICE-CREAM", "ICING", "JAM", "JELLY", "LOLLY", "OIL", 
          "PEPPER", "PIE", "PUDDING", "SACCHARINE", "SALAD", "SALT", "SAUCE", "SNACK FOOD", "SOUR", 
          "SPREAD (PASTE)", "SWEETNESS", "TASTE", "TASTE BAD", "TASTY", "YUMMY"],
      },
      {
        id: 'A03-4',
        name: 'Kitchenware / Cooking Actions',
        wordCount: 51,
        words: ["BAKE", "BEAT (MIX)", "BITE", "BOTTLE", "BOWL (DISH)", "CAN (TIN)", "CAN-OPENER", 
          "CHEWING", "CHOP", "COLANDER", "CONTAINER", "CORKSCREW", "CUTLERY", "DISH", "DISSOLVING", 
          "EGG-BEATER", "FORK", "GRILL (COOK)", "KNIFE", "LICK", "LID", "MICROWAVE", "MINCER", 
          "MIXER", "OVEN", "PEELING", "PEPPER-MILL", "PLATE", "PORTION", "POUR", "POURER", 
          "PRESSURE COOKER", "RECIPE", "REFRIGERATOR", "SAUCEPAN", "SCREW-TOP", "SIEVE", "SIFTER", 
          "SIMMER", "SINGE", "SINK", "SLICED", "SPOON", "SPOUT", "SPRINKLE", "STIRRER", "STIRRING", 
          "SUCK", "SWALLOW", "TOASTER", "WAFFLE-IRON"],
      },
    ],
  },
  {
    id: 'A04',
    category: 'A',
    categoryName: 'Everyday Scenes',
    title: 'Home / Rooms / Furniture',
    icon: '🏠',
    wordCount: 114,
    subScenarios: [
      {
        id: 'A04-1',
        name: 'Rooms / Building Structure',
        wordCount: 28,
        words: ["AUTOMATIC DOORS", "BEDROOM", "CEILING", "DINING ROOM", "DOORKNOB", "DRAIN", 
          "GARAGE", "GARDEN", "GATE", "GUTTER", "HALL", "HOME", "HOUSE", "KNOB", "LAUNDRY", "LAWN", 
          "LOCK", "RENT", "RESIDENCE", "ROOF", "ROOM", "STAIRS", "STEPS", "TERRACE", "TRAPDOOR", 
          "UPSTAIRS", "WALL", "WINDOWPANE"],
      },
      {
        id: 'A04-2',
        name: 'Furniture / Furnishings',
        wordCount: 25,
        words: ["ASHTRAY", "BASIN", "BED", "BEDFRAME", "BIN", "BOOKCASE", "BUNK", "CARPET", 
          "CHAIR", "CUPBOARD", "CURTAIN", "DECORATION", "DESK", "FLOWERPOT", "FURNITURE", 
          "MATTRESS", "RUBBISH BIN", "SEAT", "TABLE", "TABLECLOTH", "UPHOLSTERY", "VASE", 
          "VENETIAN BLIND", "VERTICAL BLINDS", "WARDROBE"],
      },
      {
        id: 'A04-3',
        name: 'Appliances / Lighting / Switches',
        wordCount: 22,
        words: ["AIR-CONDITIONING", "ALARM (RINGING)", "BELL", "CANDLE", "CEILING FAN", "DOORBELL", 
          "DOUBLE ADAPTOR", "DRYER", "HEATER", "IRON", "LAMP", "LIGHT BULB", "MATCH (MATCHSTICK)", 
          "MOWER", "PLUG", "SPIN DRYER", "SWITCH OFF", "SWITCH ON", "TAP (FAUCET)", 
          "TURN ON (START)", "WASHING MACHINE", "WATER (HOSE)"],
      },
      {
        id: 'A04-4',
        name: 'Housework / Cleaning / Bedding',
        wordCount: 39,
        words: ["ASLEEP", "BLANKET", "BROOM", "BUCKET", "CLEANING", "CLOSE (AUTOMATIC DOORS)", 
          "CLOSE (DRAWER)", "CLOSE (SLIDING-DOOR)", "CLOSE (WINDOW)", "CLOTH", "DOONA", "DUST", 
          "GET UP", "GO TO BED", "KNOCK", "MAKE THE BED", "MOP", "NAP", "OPEN (AUTOMATIC DOORS)", 
          "OPEN (DOOR)", "OPEN (DRAWER)", "OPEN (SLIDING-DOOR)", "OPEN (WINDOW)", "PEG", "PILLOW", 
          "PISS POT", "PLUNGER", "RAKE", "SHEET", "SLEEP IN", "SLEEPING", "SNORE", "SPADE", 
          "SPONGE", "TOSS AND TURN", "WAKEFULNESS", "WASHING", "WASHING UP", "WIPING"],
      },
    ],
  },
  {
    id: 'A05',
    category: 'A',
    categoryName: 'Everyday Scenes',
    title: 'Hospital / Seeing a Doctor / Medicine',
    icon: '🏥',
    wordCount: 111,
    subScenarios: [
      {
        id: 'A05-1',
        name: 'Symptoms / Discomfort',
        wordCount: 28,
        words: ["ACHE", "BLACK EYE", "BLISTER", "CHUNDER", "COUGH", "CRAMP", "DIARRHOEA", 
          "DIZZINESS", "EARACHE", "EMACIATED", "FAINT", "GRAZE", "HEADACHE", "HICCUP", 
          "INDIGESTION", "LIMP", "LUMP", "NAUSEA", "PALENESS", "RUNNY NOSE", "SCALDING", "SLEEPY", 
          "SNEEZE", "SORE", "THROB", "TIRED", "TOOTHACHE", "YAWN"],
      },
      {
        id: 'A05-2',
        name: 'Illness / Diagnosis',
        wordCount: 39,
        words: ["ABORTION", "ACNE", "ADDICTION", "ALCOHOLIC", "AMNESIA", "AMPHETAMINE", "ASTHMA", 
          "AUTISM", "BLIND", "CANCER", "CHICKEN-POX", "COLD (ILLNESS)", "DEPRESSION", "DIAGNOSIS", 
          "DISABILITY", "DRUG", "EYESIGHT", "GENE", "HANDICAP", "HASHISH", "HAY FEVER", 
          "HEART ATTACK", "HEREDITARINESS", "ILLNESS", "INFECTION", "JOINT (MARIJUANA)", "MEASLES", 
          "MENTALLY DISABLED", "MUMPS", "PARALYSIS", "PERIOD (MENSTRUATION)", "POISON", 
          "SCHIZOPHRENIA", "SENILE", "SICK", "SICKNESS", "STROKE (ILLNESS)", "SUICIDE", 
          "TUNNEL-VISION"],
      },
      {
        id: 'A05-3',
        name: 'Treatment / Medication / Instruments',
        wordCount: 28,
        words: ["ACUPUNCTURE", "AMPUTATION", "ANTISEPTIC", "BANDAGE", "BLOOD PRESSURE", 
          "BLOOD SAMPLE", "CAESAREAN", "CIRCUMCISION", "CONTACT LENSES", "CRUTCHES", "DILATION", 
          "DISMEMBERMENT", "DROPS", "FALSE TEETH", "FIRST AID", "MAMMOGRAM", "MEDICATION", "MEDS", 
          "OINTMENT", "OPERATION", "PULSE", "STERILISATION", "STETHOSCOPE", "SYRINGE", "TAMPON", 
          "THERAPY", "THERMOMETER", "ULTRASOUND SCAN"],
      },
      {
        id: 'A05-4',
        name: 'Medical Staff / Seeking Care',
        wordCount: 16,
        words: ["AMBULANCE", "CHIROPRACTOR", "CONSULTATION", "COUNSELLOR", "DENTIST", "DOCTOR", 
          "GET BETTER", "HOSPITALISE", "MATRON", "NURSE", "OPTOMETRIST", "PATIENT", "PSYCHIATRY", 
          "RECUPERATE", "WELL (HEALTHY)", "WELL-BEING"],
      },
    ],
  },
  {
    id: 'A06',
    category: 'A',
    categoryName: 'Everyday Scenes',
    title: 'School / Classroom / Study',
    icon: '🏫',
    wordCount: 100,
    subScenarios: [
      {
        id: 'A06-1',
        name: 'School / Institutions / School Stages',
        wordCount: 16,
        words: ["BOARDING SCHOOL", "CERTIFICATE", "COLLEGE", "COURSE", "CURRICULUM", 
          "DEGREE (DIPLOMA)", "DORMITORY", "HIGH SCHOOL", "KINDERGARTEN", "PRIMARY", "SCHOOL", 
          "SECONDARY", "SEMESTER", "SYLLABUS", "TAFE", "TIMETABLE"],
      },
      {
        id: 'A06-2',
        name: 'People / Roles',
        wordCount: 6,
        words: ["MORTARBOARD", "PREFECT", "PRINCIPAL", "PUPIL", "STUDENT", "TEACHER"],
      },
      {
        id: 'A06-3',
        name: 'Courses / Subjects',
        wordCount: 26,
        words: ["ANTHROPOLOGY", "BIOLOGY", "CHEMISTRY", "CORPUS", "EDUCATE", "EXPERIMENT", 
          "GRAMMAR", "GRAVITY", "HYPOTHESIS", "INSTRUCTION", "LEARN", "LEARNING", "LECTURE", 
          "LESSON", "LITERACY", "PHILOSOPHY", "PHYSICS", "POETRY", "PSYCHOLOGY", "RESEARCH", 
          "SCIENCE", "SOCIOLOGY", "STUDIES", "TEACHING", "THEORY", "VELOCITY"],
      },
      {
        id: 'A06-4',
        name: 'Stationery / Reading & Writing / Assessment',
        wordCount: 52,
        words: ["ALPHABET", "APOSTROPHE", "ASSIGNMENT", "BIBLIOGRAPHY", "BLACKBOARD", "BOOK", 
          "BRACKET", "CHAPTER", "CHARACTERS", "CLOSE (BOOK)", "COLON (PUNCTUATION MARK)", "COMMA", 
          "COMPASSES", "CRAYON", "CROSS OUT", "DIAGRAM", "DICTIONARY", "DISCIPLINE", "DRAW LINE", 
          "DRAWING", "FULL STOP", "HANDWRITING", "JOURNAL", "MICROSCOPE", "NOTATION", "NOTES", 
          "NOVEL", "OVERHEAD-PROJECTOR", "PAGE", "PAPER", "PARAGRAPH", "PASS (TEST)", "PEN", 
          "PENCIL", "QUESTION MARK", "QUESTIONNAIRE", "QUOTE", "READING", "RUBBER (ERASER)", 
          "RULER", "SCRIBBLE", "SCRIPT", "SENTENCE", "SKIM OVER", "SUMMARY", "TELESCOPE", 
          "TESTING", "TITLE", "TRACING", "WORDS", "WRITE", "WRITING"],
      },
    ],
  },
  {
    id: 'A07',
    category: 'A',
    categoryName: 'Everyday Scenes',
    title: 'Transport / Travel / Asking Directions',
    icon: '🚗',
    wordCount: 79,
    subScenarios: [
      {
        id: 'A07-1',
        name: 'Vehicles',
        wordCount: 18,
        words: ["AIRPLANE", "BICYCLE", "BOAT", "CAR (AT)", "HELICOPTER", "MOTORCYCLE", "PROPELLER", 
          "ROCKET", "SCOOTER", "SPEEDBOAT", "SUBMARINE", "TAXI", "TRAILER", "TRAIN", 
          "TRAIN (ELECTRIC)", "TRAM", "VAN", "YACHT"],
      },
      {
        id: 'A07-2',
        name: 'Roads / Stations & Facilities',
        wordCount: 27,
        words: ["AIRPORT", "AVENUE", "BRIDGE", "CAR PARK", "CITY", "CROSSING", "DEAD END", 
          "ESCALATOR", "EXIT", "FOOTPATH", "HIGHWAY", "LANE", "LIFT (ELEVATOR)", "ONE WAY", 
          "PLATFORM", "ROAD", "ROUNDABOUT", "SIGN (SIGNPOST)", "SIGNPOST", "STATION", 
          "STATION (RAILWAY)", "STREET", "THOROUGHFARE", "TOWN", "TRAFFIC LIGHTS", "WHARF", 
          "WITCH'S HAT"],
      },
      {
        id: 'A07-3',
        name: 'Driving / Riding Actions',
        wordCount: 21,
        words: ["DRIVE IN", "GET LOST", "GET OFF", "GO (IN VEHICLE)", "LANDING", "LIFT (IN A CAR)", 
          "OVERTAKING (IN VEHICLE)", "PARK (VEHICLE)", "PARKING", "PICK UP (SOMEONE)", 
          "REVERSE VEHICLE", "SEAT BELT (CAR)", "SEAT BELT (PLANE)", "SLOW DOWN", "SPEED", 
          "SPEEDING", "STEER", "TAKE OFF (PLANE)", "TRAIN (TRAVEL BY)", "TURN LEFT", "TURN RIGHT"],
      },
      {
        id: 'A07-4',
        name: 'People / Documents / Road Conditions',
        wordCount: 13,
        words: ["ACCIDENT", "BUS DRIVER", "CRASH (PLANE)", "CRASH (VEHICLE)", "DRIVER", "DRIVERS", 
          "FLIGHT ATTENDANT", "HITCH-HIKER", "LICENCE", "MOBILITY", "PASSENGER", "TICKET", 
          "TRAFFIC JAM"],
      },
    ],
  },
  {
    id: 'A08',
    category: 'A',
    categoryName: 'Everyday Scenes',
    title: 'Bank / Post Office / Errands',
    icon: '🏦',
    wordCount: 49,
    subScenarios: [
      {
        id: 'A08-1',
        name: 'Money / Currency',
        wordCount: 10,
        words: ["BANKNOTE", "CENT", "COIN", "CURRENCY", "DOLLAR", "FUNDS", "MONEYED", "POVERTY", 
          "RICHES", "WALLET"],
      },
      {
        id: 'A08-2',
        name: 'Bank / Income & Expenses',
        wordCount: 22,
        words: ["BANK", "BANKRUPTCY", "BEQUEST", "BORROWING", "BUDGET", "CHEQUE", "DEBT", 
          "DEPOSIT", "DUES", "EXPENSE", "EXPENSES", "FRUGALITY", "INCOME", "INFLATION", 
          "INSURANCE", "OWE", "PROFIT", "SALARY", "SAVING", "SPENDTHRIFT", "TREASURER"],
      },
      {
        id: 'A08-3',
        name: 'Postal / Paperwork',
        wordCount: 17,
        words: ["ADDRESS", "BUREAUCRACY", "CERTIFY", "CORRESPOND", "COUNCIL", "DISPATCH", 
          "ENVELOPE", "LETTER BOX", "LETTER OPENER", "LETTERS", "MAIL OUT", "PARCEL", 
          "POST OFFICE", "POSTBOX", "SEND", "STAMP (POSTAGE)", "WIRE (TELEGRAM)"],
      },
    ],
  },
  {
    id: 'A09',
    category: 'A',
    categoryName: 'Everyday Scenes',
    title: 'Work / Workplace / Occupations',
    icon: '💼',
    wordCount: 98,
    subScenarios: [
      {
        id: 'A09-1',
        name: 'Occupations / Trades',
        wordCount: 29,
        words: ["ACTOR", "APPRENTICE", "ARMY", "AUTHOR", "BOOTMAKER", "BRICKLAYER", "CAMERAMAN", 
          "CHEF", "COLLECTOR", "CONDUCTOR", "CONSULTANT", "CORPORAL", "COWBOY", "DIRECTOR", 
          "FIREFIGHTER", "INTERVIEWER", "LIBRARIAN", "MAID", "NEWBIE", "PRIVATE (ARMY RANK)", 
          "PROFESSIONAL", "SAILOR", "SECRETARY", "SERGEANT", "SHEPHERD", "SOLDIER", "TRAINEE", 
          "VOLUNTEER", "WELDER"],
      },
      {
        id: 'A09-2',
        name: 'Organisations / Positions',
        wordCount: 19,
        words: ["ABATTOIR", "ADMINISTRATION", "ASSOCIATION", "AUTHORITY", "BOARD (COMMITTEE)", 
          "BOSS", "COMMITTEE", "COMPANY (BUSINESS)", "FACTORY", "FARM", "HIERARCHY", "INSTITUTION", 
          "LEADER", "MANAGEMENT", "ORGANISATION", "PRESIDENT", "STAKEHOLDER", "SUPERVISION", 
          "WORKSHOP"],
      },
      {
        id: 'A09-3',
        name: 'Office / Affairs',
        wordCount: 25,
        words: ["AGENDA", "BLUEPRINT", "CHECKLIST", "CLOSE (FOLDER)", "CONFERENCE", "DEBRIEF", 
          "DRAFTING (DRAW)", "EDIT", "FEEDBACK", "FILE", "FOLDER", "INTERVIEW", "MARKETING", 
          "NEGOTIATION", "OPEN (FOLDER)", "PHOTOCOPIER", "POLICY", "PRINT", "PRODUCTION", "REPORT", 
          "SERVICE", "STAPLER", "THUMB TACKS", "TYPE UP", "TYPEWRITER"],
      },
      {
        id: 'A09-4',
        name: 'Employment / Attendance / Labour Relations',
        wordCount: 25,
        words: ["ASSEMBLY LINE", "BLUDGE", "BUSY", "DEMOTION", "DISMISS", "FIRING", "FORK-LIFT", 
          "FULL-TIME", "HARVEST", "HECTIC", "JOIN (ENLIST)", "LABOUR", "MACHINE", 
          "MINE (EXCAVATE)", "OFFICIAL", "OVERTIME", "RECRUIT", "RETIREMENT", "SHEEP SHEARING", 
          "SHIFT (WORK)", "SICKIE", "STEP DOWN", "STRIKE (STOP WORK)", "UNEMPLOYMENT", "WORK"],
      },
    ],
  },
  {
    id: 'A10',
    category: 'A',
    categoryName: 'Everyday Scenes',
    title: 'Clothing / Wearables',
    icon: '👔',
    wordCount: 99,
    subScenarios: [
      {
        id: 'A10-1',
        name: 'Tops / Outerwear',
        wordCount: 20,
        words: ["APRON", "COAT (CLOTHING)", "COSTUME", "DRESS", "DRESSING GOWN", "JUMPER", "KILT", 
          "LONG SLEEVE SHIRT", "NIGHTDRESS", "OVERALLS", "SHIRT", "SHORT SLEEVE SHIRT", "SINGLET", 
          "SKIVVY", "SLEEVELESS SHIRT", "SUIT", "TUNIC", "TUTU", "UNIFORM", "V-NECK"],
      },
      {
        id: 'A10-2',
        name: 'Bottoms / Footwear & Socks / Underwear',
        wordCount: 24,
        words: ["BIKINI", "BRA", "CORSET", "HALF-SLIP", "JEANS", "PANTS", "PANTYHOSE", "PETTICOAT", 
          "SANDAL", "SHORTS", "SKIRT", "SLIP (PETTICOAT)", "SLIPPER", "SOCK", "STILETTO", 
          "STOCKINGS", "SWIMMING COSTUME", "SWIMMING TRUNKS", "SWIMSUIT", "THONGS", "TIGHTS", 
          "TROUSERS", "UNDERPANTS", "UNDERWEAR"],
      },
      {
        id: 'A10-3',
        name: 'Accessories / Jewellery',
        wordCount: 21,
        words: ["BADGE", "BEADED NECKLACE", "BELT", "BERET", "BOW (RIBBON)", "BOW TIE", "BRACELET", 
          "BROOCH", "CAP", "DIAMOND", "EARRING", "GLOVE", "HANDKERCHIEF", "NECKLACE", "PENDANT", 
          "PURSE", "SASH", "SCARF", "SUSPENDERS", "TIE (NECKTIE)"],
      },
      {
        id: 'A10-4',
        name: 'Dressing Actions / Garment Parts',
        wordCount: 34,
        words: ["ALTERATIONS (CLOTHING)", "BUTTON (CLOTHING)", "BUTTON UP", "CHECK (PATTERN)", 
          "COAT-HANGER", "COLLAR", "COTTON", "CUFF", "DOFF", "ELASTIC", "FASHION", "FASTEN", 
          "FLY (TROUSERS)", "FLY (ZIPPER)", "GET DRESSED", "LEATHER", "NAKED", "NUDE", 
          "OPEN-NECKED", "PATCH", "PATTERN", "POCKET", "SIZE (IN WIDTH OR CLOTHES)", "SLEEVE", 
          "STRIPES", "STYLE", "TOPLESS", "TUCK", "UNBUCKLE", "UNZIP", "WEAR", "WOOL", "ZIP", 
          "ZIPPER"],
      },
    ],
  },
  {
    id: 'A11',
    category: 'A',
    categoryName: 'Everyday Scenes',
    title: 'Haircut / Beauty / Personal Care',
    icon: '💇',
    wordCount: 53,
    subScenarios: [
      {
        id: 'A11-1',
        name: 'Hair / Hairstyles / Shaving',
        wordCount: 27,
        words: ["BALD", "BARBER", "BEARD", "BLONDE", "BRAIDED", "BUN (HAIR)", "COMB", "CREWCUT", 
          "CURL", "CURLS", "CUT-THROAT RAZOR", "DYE", "GREY-HAIRED", "HAIR", "HAIR (LONG)", 
          "HAIR (SHORT)", "HAIR SPRAY", "HAIRBRUSH", "HAIRDRESSING", "MOUSTACHE", "SHAVE (FACE)", 
          "SHAVE (HEAD)", "SHAVE (LEG)", "SHAVE (UNDERARM)", "SHAVER", "SIDEBOARDS", "WIG"],
      },
      {
        id: 'A11-2',
        name: 'Makeup / Skincare / Fragrance',
        wordCount: 14,
        words: ["DEODORANT", "EYEBROW PENCIL", "EYELINER", "FRAGRANCE", "GLASSES", "LIPSTICK", 
          "LOTION", "MAKE-UP", "MIRROR", "NAIL POLISH", "PERFUMED", "TALCUM POWDER", "TATTOO", 
          "TOUCH UP"],
      },
      {
        id: 'A11-3',
        name: 'Grooming / Hygiene Products',
        wordCount: 12,
        words: ["BATH", "MASSAGE", "NAIL BRUSH", "SHAMPOO", "SHOWER", "SPA", "TISSUE", 
          "TOOTHBRUSH", "TOOTHPASTE", "TOWEL", "WASH"],
      },
    ],
  },
  {
    id: 'A12',
    category: 'A',
    categoryName: 'Everyday Scenes',
    title: 'Sport / Fitness',
    icon: '⚽',
    wordCount: 108,
    subScenarios: [
      {
        id: 'A12-1',
        name: 'Ball Sports',
        wordCount: 27,
        words: ["BADMINTON", "BASEBALL", "BASKETBALL", "BAT", "BILLIARDS", "BOWLS", "BUNKER", 
          "CADDIE", "CRICKET", "FOOTBALL", "GOAL", "GOALKEEPER", "GOLF", "HOCKEY", "ICE HOCKEY", 
          "LACROSSE", "NET", "NETBALL", "RUGBY", "RUGBY UNION", "SINGLES", "SOCCER", 
          "SQUASH (SPORT)", "TABLE TENNIS", "TENNIS", "VOLLEYBALL", "WATER-POLO"],
      },
      {
        id: 'A12-2',
        name: 'Water Sports / Athletics / Other Events',
        wordCount: 48,
        words: ["BACKSTROKE", "BALLET", "BOXING", "BREAST STROKE", "BUTTERFLY STROKE", 
          "CALLISTHENICS", "CANOE", "CHOREOGRAPHY", "CLIMB", "CLIMBING", "DANCE", "DART", "DISCUS", 
          "DIVE", "DIVING", "FISHING", "FLAMENCO", "FLOAT", "GOGGLES", "GYMNASIUM", "HIGH JUMP", 
          "HURDLES", "ICE SKATES", "ICE-SKATES", "JOCKEY", "JUMP", "KARATE", "LIFESAVER", 
          "LONG JUMP", "OVERARM (SWIMMING)", "PARACHUTE", "POLE VAULT", "RIDE (HORSE)", 
          "ROLLER SKATES", "ROWBOAT", "ROWING", "RUN", "SHOT-PUT", "SKIPPING", "SKIPPING ROPE", 
          "SPEEDWAY", "SPRINT", "SURF", "SURFING", "SWIMMING POOL", "TRACK", "WATER-SKI", 
          "WRESTLING"],
      },
      {
        id: 'A12-3',
        name: 'Competition / Winning & Losing',
        wordCount: 24,
        words: ["AMATEUR", "BEAT (DEFEAT)", "BULL'S-EYE", "CHAMPION", "COMPETE", "COMPETITION", 
          "DEFEAT", "KNOCKOUT", "LEAD (COMPETITION)", "NECK AND NECK", "OLYMPIC GAMES", "PENNANT", 
          "PRESENT (AWARD)", "PRIZE", "REFEREE", "RELAY", "SCORE (TALLY)", "SPORT", "SUBSTITUTION", 
          "TEAM", "TIME OUT", "TROPHY", "WHISTLE", "WINNER"],
      },
      {
        id: 'A12-4',
        name: 'Training / Equipment / Actions',
        wordCount: 9,
        words: ["ENDURANCE", "EXERCISE (PHYSICAL)", "FIT (HEALTHY)", "FITNESS", "FLEXIBILITY", 
          "PRACTICE", "STRETCH", "TACKLE"],
      },
    ],
  },
  {
    id: 'A13',
    category: 'A',
    categoryName: 'Everyday Scenes',
    title: 'Tourism / Accommodation',
    icon: '🏨',
    wordCount: 23,
    subScenarios: [
      {
        id: 'A13-1',
        name: 'Itinerary / Outings',
        wordCount: 10,
        words: ["EXPLORE", "HIKER", "HOLIDAY", "JOURNEY", "OVERSEAS", "ROUND TRIP", "TRAVEL TO", 
          "TRAVELLING", "TRIP (JOURNEY)"],
      },
      {
        id: 'A13-2',
        name: 'Accommodation / Booking',
        wordCount: 5,
        words: ["ACCOMMODATION", "BOARD (LIVE AT)", "CARAVAN", "HOSPITALITY", "RESERVE (BOOK)"],
      },
      {
        id: 'A13-3',
        name: 'Attractions / Luggage',
        wordCount: 8,
        words: ["BINOCULARS", "BROCHURE", "CASTLE", "PACK", "SCENERY", "TOWER", 
          "TRUNK (CONTAINER)", "ZOO"],
      },
    ],
  },
  {
    id: 'A14',
    category: 'A',
    categoryName: 'Everyday Scenes',
    title: 'Socialising / Small Talk / Everyday Conversation',
    icon: '👥',
    wordCount: 168,
    subScenarios: [
      {
        id: 'A14-1',
        name: 'Greetings / Polite Expressions',
        wordCount: 30,
        words: ["AHH", "ALRIGHT", "APOLOGY", "BYE-BYE", "COME HERE", "CONGRATULATIONS", "EXCUSE", 
          "FINE (OK)", "GO ON (EXCLAMATION)", "HANDSHAKE", "HELLO", "HEY", "HI", "HOLD ON (WAIT)", 
          "INTRODUCTION", "KEEP QUIET", "NO WAY (REJECT)", "NOD", "OH", "PHOOEY", "SEE YOU AGAIN", 
          "SHUT UP", "THANK YOU", "THANKS", "THAT'S RIGHT", "WAIT", "WAIT (LONG TIME)", "WELCOME", 
          "WELL (PALM UP)", "YOU KNOW"],
      },
      {
        id: 'A14-2',
        name: 'Conversation / Expression',
        wordCount: 38,
        words: ["ASK", "ASK AROUND", "BUGGER (BASTARD)", "BULLSHIT (NONSENSE)", "CALL OUT", 
          "CHINWAG", "COMMUNICATION", "COMPLAINT", "CONVERSATION", "CRAP", "DIALOGUE", "DICKHEAD", 
          "ENQUIRY", "EXPLANATION", "GIBBERISH", "GOSSIP", "HEAR ABOUT", "JOKE", "KIDDING", 
          "LET KNOW", "NAG", "NARRATE", "NONE OF ONE'S BUSINESS", "QUARREL", "QUESTION", "SAYING", 
          "SCREAM OUT", "SERVE (SERVE YOU RIGHT)", "SERVE YOU RIGHT", "SHITHOUSE", "SHOUT", 
          "SPEAKING", "SPEECH", "SWEARING", "TALE", "TALK", "TELL OFF", "WHISPER"],
      },
      {
        id: 'A14-3',
        name: 'Interpersonal / Gatherings',
        wordCount: 45,
        words: ["APPLAUSE", "AUDIENCE", "AUDIENCE (EXCITED)", "BUDDIES", "CATCH UP", "CELEBRATION", 
          "CHRISTMAS", "CIGARETTE", "CIGARETTE (ROLL-YOUR-OWN)", "CLUB", "COFFIN", "COMMEMORATION", 
          "COMMUNITY", "COMPANY", "CONTACT", "CULTURE", "ENCOUNTER", "ENEMY", "FINISH (CIGARETTE)", 
          "FRIEND", "FUNERAL", "GENTLEMAN", "GIRL GUIDE", "GO OUT", "GRAVE", "HELP", "INVITATION", 
          "INVITE INTO", "LADY", "LIGHTER", "MAN", "MATE", "MEET", "MINGLE", "NEIGHBOUR", 
          "NICKNAME", "PARADE", "PARTY", "PASS AWAY", "PIPE", "PRESENT (GIFT)", "RECONCILE", 
          "SCOUT", "SMOKE (PIPE)", "VISITOR"],
      },
      {
        id: 'A14-4',
        name: 'Entertainment / Games / Arts',
        wordCount: 55,
        words: ["BALLOON", "BOARD GAME", "BOOMERANG", "CASINO", "CIRCUS", "CLOWN", "CLUBS", 
          "COMIC", "DEAL (CARDS)", "DICE", "DOMINO", "DRAMA", "DRAW (LOTTERY)", "DRUMSTICK", 
          "FERRIS WHEEL", "FLICKS", "FLUTE", "GUITAR", "HARP", "HEARTS", "HIDE-AND-SEEK", "JIGSAW", 
          "JUGGLER", "LUNA PARK", "MARBLES", "MOVIE THEATRE", "MUSIC", "OPERA", "ORCHESTRA", 
          "PAINTING (ART)", "PERFORMANCE", "PIANO", "PICTURE", "PLAYING CARD", "POKER MACHINE", 
          "PORTRAIT", "PROMPTER", "PUZZLE", "QUOITS", "RECORD (VINYL RECORD)", "REHEARSAL", 
          "RHYTHM", "SCULPTURE", "SHUFFLE (CARDS)", "SONG", "STAGE", "STRING PUPPET", "TAMBOURINE", 
          "THEATRICAL", "TOM-TOM DRUM", "TROMBONE", "TRUMPET", "TWO-UP", "WIND INSTRUMENT"],
      },
    ],
  },
  {
    id: 'A15',
    category: 'A',
    categoryName: 'Everyday Scenes',
    title: 'Family / Relatives',
    icon: '👪',
    wordCount: 27,
    subScenarios: [
      {
        id: 'A15-1',
        name: 'Kinship Terms',
        wordCount: 15,
        words: ["AUNT", "BROTHER", "COUSIN", "DAUGHTER", "FATHER", "MOTHER", "MUM", "NEPHEW", 
          "NIECE", "PARENT", "PARENTS", "SISTER", "SON", "TWINS", "UNCLE"],
      },
      {
        id: 'A15-2',
        name: 'Family / Generations',
        wordCount: 12,
        words: ["ADOPT", "ADOPTION", "ADULT", "ADULTS", "ANCESTORS", "BOY", "CHILD", "CHILDHOOD", 
          "CHILDREN", "GENERATION", "KID"],
      },
    ],
  },
  {
    id: 'A16',
    category: 'A',
    categoryName: 'Everyday Scenes',
    title: 'Weather / Seasons / Nature',
    icon: '🌳',
    wordCount: 63,
    subScenarios: [
      {
        id: 'A16-1',
        name: 'Weather Phenomena',
        wordCount: 22,
        words: ["BLAZE (SUN)", "CHILL", "CLOUD", "COLD", "CYCLONE", "DRIZZLE", "FLOOD", "GALE", 
          "HAIL", "HOT", "HUMID", "LIGHTNING", "RAIN", "RAINBOW", "SHADE", "SNOW", "TEMPERATURE", 
          "THUNDER", "UMBRELLA", "VAPOUR", "WEATHER", "WIND (AIR)"],
      },
      {
        id: 'A16-2',
        name: 'Seasons / Day & Night / Celestial Bodies',
        wordCount: 8,
        words: ["AUTUMN", "DARK", "MOON", "STAR", "SUMMER", "SUNRISE", "SUNSET", "WINTERTIME"],
      },
      {
        id: 'A16-3',
        name: 'Landforms / Natural Environment',
        wordCount: 33,
        words: ["AIR", "BANK (SHORE)", "BED (SEABED)", "BLOSSOM", "CHOP DOWN", "CLIFF", "DIRT", 
          "EARTHQUAKE", "ENVIRONMENT", "FELLING (TREES)", "FLOWER", "FOREST", "FOUNTAIN", "GROUND", 
          "HILL", "ISLAND", "JUNGLE", "LAVA", "MOUNTAIN", "MOUNTAINS", "RAVINE", "RIVER", "ROCK", 
          "SAND", "SHELL", "SHRUB", "SKY", "SOIL", "SOWING", "SURROUNDINGS", "VALLEY", "WARATAH", 
          "WAVE (WATER)"],
      },
    ],
  },
  {
    id: 'A17',
    category: 'A',
    categoryName: 'Everyday Scenes',
    title: 'Emotions / Feelings',
    icon: '😊',
    wordCount: 166,
    subScenarios: [
      {
        id: 'A17-1',
        name: 'Positive Emotions',
        wordCount: 36,
        words: ["ADORATION", "AMAZING (EXCLAMATION)", "BRAVERY", "CARE", "COMPASSION", 
          "CONFIDENCE", "COURAGE", "EAGERNESS", "EMPATHY", "ENCOURAGE", "ENJOYMENT", 
          "ENTHUSIASTIC", "EXCITEMENT", "FONDNESS", "FUN", "GENEROUS", "GIGGLE", "GLEEFUL", 
          "GOOD-HEARTEDNESS", "GRIN", "GUFFAW", "HAPPINESS", "IMPRESSED", "JOY", "KEENNESS", 
          "LAUGHTER", "PLEASED", "RELAXATION", "RELIEF", "REST", "SATISFACTION", "SMILE", 
          "SUPPORTIVE", "SYMPATHETIC", "THRILL", "TRUST"],
      },
      {
        id: 'A17-2',
        name: 'Negative Emotions',
        wordCount: 48,
        words: ["ANGER", "ANNOYING", "BLUSH", "BOREDOM", "CONFUSION", "CRANKINESS", 
          "DISAPPOINTMENT", "DISCOURAGEMENT", "DISGUSTING", "DISLIKE", "DISTASTEFUL", "EMBARRASS", 
          "EMBARRASSMENT", "ENVY", "FEAR", "FRUSTRATED", "FRUSTRATION", "FURY", "GRIEF", "GUILT", 
          "HOPELESS", "HUMILIATION", "IRRITATED", "LIKE (NOT LIKE)", "LOATHING", "LONELINESS", 
          "MORTIFICATION", "OVERWHELM", "PANIC", "PITY", "RAGE", "REGRET", "RESENT", "REVULSION", 
          "SAD", "SCARE", "SHOCK", "SORROW", "SPITE", "SUFFER", "TEARS", "TENSION", "TERROR", 
          "TRIBULATION", "UNHAPPINESS", "UPSET", "VENGEANCE"],
      },
      {
        id: 'A17-3',
        name: 'Personality / Attitudes',
        wordCount: 55,
        words: ["ALOOF", "AMBITIOUS", "ASSERTIVENESS", "ATTITUDE", "BLAME", "BOAST", "BOSSY", 
          "BRAG", "CHEAT", "CONSCIENCE", "CRAZY", "CRITICISM", "CRUEL", "DISMISSIVE", "FOOL", 
          "FUSSY", "HYPOCRITE", "IDIOT", "IDIOTIC", "INDIFFERENT", "LIE", "LOONY", "MEANNESS", 
          "MOCK", "NARROW-MINDEDNESS", "NASTINESS", "NERVY", "OBSESSIVE", "OPEN-MINDEDNESS", 
          "PRUDE", "RECKLESSNESS", "RESILIENCE", "RUDENESS", "SCORN", "SELFISHNESS", "SERIOUS", 
          "SHYNESS", "SILLINESS", "SILLY", "SINGLE-MINDED", "SINGLE-MINDEDNESS", "SNOB", "SNUB", 
          "STICKY-BEAK", "STRICTNESS", "STUBBORNNESS", "STUPID", "STUPID ME", "SUSPICIOUS", 
          "SYCOPHANT", "TELLTALE", "TEMPER", "TIMIDITY", "WICKEDNESS", "WILFULNESS"],
      },
      {
        id: 'A17-4',
        name: 'Psychological Reactions / Feelings',
        wordCount: 27,
        words: ["ASTONISHING", "BEFUDDLEMENT", "BEWILDER", "CHASTENED", 
          "CONFIDENCE (LOSE CONFIDENCE)", "CONFOUND", "CONFRONTING", "CURIOUS", "DAYDREAM", 
          "DISBELIEF", "DOUBT", "DREAM", "EMOTION", "EYE-POPPING", "FANTASY", "FASCINATING", 
          "FASCINATION", "FEEL", "FLABBERGASTED", "HEART (AT HEART)", "PROVOCATION", "PUZZLED", 
          "SELF-REFLECTION", "STIR-CRAZY", "SURPRISED", "TEMPTED", "TEMPTING"],
      },
    ],
  },
  {
    id: 'A18',
    category: 'A',
    categoryName: 'Everyday Scenes',
    title: 'Time / Dates / Numbers / Quantity',
    icon: '📅',
    wordCount: 138,
    subScenarios: [
      {
        id: 'A18-1',
        name: 'Numbers / Ordinals',
        wordCount: 51,
        words: ["BILLION", "DOUBLE", "EIGHT", "EIGHTEEN", "EIGHTH", "ELEVEN", "FIFTEEN", "FIFTH", 
          "FIFTH (LIST)", "FIRST", "FIRST (EVERY FIRST)", "FIRST (LIST)", "FIVE", "FOUR", "FOURS", 
          "FOURTEEN", "FOURTH", "FOURTH (EVERY FOURTH)", "FOURTH (LIST)", "HALF", 
          "HUNDRED (ONE HUNDRED)", "HUNDREDS", "MILLION", "NINE", "NINETEEN", "NINTH", "NOUGHT", 
          "NUMBER", "ONCE", "ONE", "SECOND", "SECOND (EVERY SECOND)", "SECOND (LIST)", "SEVEN", 
          "SEVENTEEN", "SEVENTH", "SIX", "SIXTEEN", "SIXTH", "TEN", "THIRD", "THIRD (EVERY THIRD)", 
          "THIRD (LIST)", "THIRTEEN", "THOUSAND", "THREE", "THRICE", "TRIPLE", "TRIPLES", "TWICE", 
          "TWO"],
      },
      {
        id: 'A18-2',
        name: 'Clock Times / Time Periods',
        wordCount: 37,
        words: ["AGES", "CLOCK", "DAY (ALL DAY LONG)", "DAY (THE NEXT DAY)", "DAYBREAK", "DAYTIME", 
          "DELAY", "DIGITAL WATCH", "EARLY", "ETERNITY", "EVENING", "HALF HOUR", "HALF PAST", 
          "HOUR", "INSTANT", "INTERVAL", "LATE", "LATER", "LONG TIME", "NIGHT", "NOON", "NOW", 
          "OVERNIGHT", "POSTPONEMENT", "PUNCTUAL", "PUT OFF", "QUARTER HOUR", "SOON", "TEMPORARY", 
          "TIME", "TIME (BETWEEN TWO CLOCK TIMES)", "TIME FLIES", "TIME-FRAME", "TOO LATE", 
          "WATCH-THE-TIME", "WIND UP (WATCH)", "WRISTWATCH"],
      },
      {
        id: 'A18-3',
        name: 'Days of the Week / Dates / Cycles',
        wordCount: 35,
        words: ["BEFORE", "BEFORE THAT", "BEFORE THAT (NOT BEFORE THAT)", "CALENDAR", "FORMERLY", 
          "FORTNIGHT", "FRIDAY", "FUTURE", "HOW OLD", "MONDAY", "NEXT WEEK", "OLDER", "PAST", 
          "PERIOD (TIME)", "PREVIOUS", "PRIOR TO", "PRIOR TO (NOT PRIOR TO)", "RECENT", "SATURDAY", 
          "SUNDAY", "THURSDAY", "TOMORROW", "TUESDAY", "USED TO", "WEEK", "WEEK (LAST WEEK)", 
          "WEEK (THIS WEEK)", "WEEK (WEEK AFTER)", "WEEKEND", "YEAR", "YEAR (LAST YEAR)", 
          "YEAR (NEXT YEAR)", "YEAR (ONE YEAR)", "YEAR ROUND", "YEARS"],
      },
      {
        id: 'A18-4',
        name: 'Units of Measurement / Quantity',
        wordCount: 15,
        words: ["CENTIMETRE", "DEGREE", "INCH", "KILOGRAM", "KILOMETRE", "LENGTH", "LITRE", 
          "MEASURE", "METRE", "QUANTITY", "QUARTER", "SIZE (OF CONTAINER)", "UNIT", "VOLUME", 
          "WEIGH"],
      },
    ],
  },
  {
    id: 'A19',
    category: 'A',
    categoryName: 'Everyday Scenes',
    title: 'Mobile Phone / Computer / Internet',
    icon: '📱',
    wordCount: 51,
    subScenarios: [
      {
        id: 'A19-1',
        name: 'Devices / Hardware',
        wordCount: 19,
        words: ["ANSWERING MACHINE", "CAMERA", "COMPUTER", "DISK", "FAX MACHINE", "HEAD-SET", 
          "MICROPHONE", "MOBILE PHONE", "MODEM", "MOUSE (COMPUTER)", "PAGER", "ROBOT", "SCREEN", 
          "TAPE RECORDER", "TECHNOLOGY", "TELEPHONE", "TELEVISION", "VIDEO CAMERA", 
          "VISUAL DISPLAY UNIT (VDU)"],
      },
      {
        id: 'A19-2',
        name: 'Communication / Social Platforms',
        wordCount: 18,
        words: ["DIAL", "DISCONNECT", "DISCONNECTION", "FACEBOOK", "GOOGLE", "INSTAGRAM", 
          "INTERNET", "NEWS", "NEWSPAPER", "RING (TELEPHONE)", "SMS", "TELECOMMUNICATIONS", 
          "TELEPHONE CALL", "TELSTRA", "TEXT-MESSAGE", "TWITTER", "VIDEO CALL", "VIDEO CONFERENCE"],
      },
      {
        id: 'A19-3',
        name: 'Audio & Video / Operations',
        wordCount: 14,
        words: ["CHANNEL (TV)", "CURSOR", "FAST FORWARD", "PHOTO", "PLAY TAPE", "PROGRAM", 
          "RECORDING", "REMOTE CONTROL", "REWIND", "STATUS BAR", "TURN DOWN (DECREASE)", "VIDEO", 
          "VOLUME (SOUND)", "ZOOM"],
      },
    ],
  },
  {
    id: 'A20',
    category: 'A',
    categoryName: 'Everyday Scenes',
    title: 'Romance & Marriage / Sexes',
    icon: '💍',
    wordCount: 50,
    subScenarios: [
      {
        id: 'A20-1',
        name: 'Dating / Relationships',
        wordCount: 17,
        words: ["AFFAIR", "ATTRACT", "ATTRACTION", "BOYFRIEND", "COUPLE", "DE FACTO", "DIVORCEE", 
          "FLIRT", "FLIRTING", "GIRLFRIEND", "LOVE", "LOVER", "PARTNER", "RELATIONSHIP", 
          "SEPARATE (PARTNERS)", "SPOUSE", "SWEETHEART"],
      },
      {
        id: 'A20-2',
        name: 'Marriage / Ceremonies',
        wordCount: 6,
        words: ["BRIDE", "DIAMOND RING", "GROOMSMAN", "HONEYMOON", "MARRIAGE", "WEDDING"],
      },
      {
        id: 'A20-3',
        name: 'Sex / Physical Intimacy',
        wordCount: 27,
        words: ["BISEXUALITY", "CONDOM", "CUDDLE", "DRAG (FEMALE IMPERSONATION)", "EJACULATION", 
          "FELLATIO", "FUCK (SEXUAL ACT)", "HARD ON", "HOMOSEXUAL", "INTERCOURSE", "KISS", 
          "LESBIAN", "LOSE ERECTION", "LOVE-BITE", "LUST", "MASTURBATION", "PETTING", 
          "PROMISCUOUS", "PROSTITUTE", "QUEER", "RANDINESS", "RISQUE", "SLUT", "SMOOCH", 
          "SOLICITING", "TRANSGENDER", "VIRGIN"],
      },
    ],
  },
  {
    id: 'A21',
    category: 'A',
    categoryName: 'Everyday Scenes',
    title: 'Childcare / Babies & Toddlers',
    icon: '👶',
    wordCount: 25,
    subScenarios: [
      {
        id: 'A21-1',
        name: 'Baby Products',
        wordCount: 15,
        words: ["BIB", "BOTTLE-FEEDING", "BUBBLES", "COT", "DOLL", "DUMMY", "HAND PUPPET", "NAPPY", 
          "PLASTICINE", "PLAYPEN", "SEESAW", "SLIDE", "SWING", "TEDDY-BEAR", "TOY"],
      },
      {
        id: 'A21-2',
        name: 'Parenting / Play',
        wordCount: 10,
        words: ["BABY", "FEED", "LOOK AFTER", "NURSE (CRADLE)", "PLAY", "PLAYTIME", "PREGNANCY", 
          "SMACK", "UPBRINGING"],
      },
    ],
  },
  {
    id: 'A22',
    category: 'A',
    categoryName: 'Everyday Scenes',
    title: 'Animals',
    icon: '🐕',
    wordCount: 96,
    subScenarios: [
      {
        id: 'A22-1',
        name: 'Mammals',
        wordCount: 38,
        words: ["ALSATIAN (DOG)", "BARK (DOG)", "BEAR", "BREED", "BULL", "CAMEL", "CAT", "COW", 
          "CUB", "DOG", "DOLPHIN", "DONKEY", "ECHIDNA", "ELEPHANT", "GALLOPING", "GIRAFFE", "GOAT", 
          "GORILLA", "HIPPOPOTAMUS", "HORSE", "KANGAROO", "LION", "MONKEY", "MOUSE", "PIG", 
          "POSSUM", "RABBIT", "RAM", "RAT", "RHINOCEROS", "SEAL (ANIMAL)", "STRAY", "TAME", "TROT", 
          "WHALE", "WOLF", "WOMBAT", "ZEBRA"],
      },
      {
        id: 'A22-2',
        name: 'Birds / Fish / Aquatic Life',
        wordCount: 25,
        words: ["BIRD", "BUDGERIGAR", "CHICK", "CLAM", "CRAB", "CROCODILE", "CRUSTACEAN", "DUCK", 
          "DUCKLING", "EMU", "FISH", "FLATHEAD", "JELLYFISH", "KIWI", "MARLIN", "OCTOPUS", "OWL", 
          "PARROT", "PECKING", "PENGUIN", "SHARK", "STINGRAY", "SWAN", "TORTOISE", "TURKEY (ANIMAL)"],
      },
      {
        id: 'A22-3',
        name: 'Insects / Reptiles / Animal Body Parts',
        wordCount: 33,
        words: ["ANIMAL", "ANTLERS", "BURROW", "BUTTERFLY", "CAGE", "CLAW", "COBRA", "COCKROACH", 
          "CREEPY-CRAWLY", "DINOSAUR", "DRAGON", "ENCLOSURE", "EXTINCT", "FIN (DORSAL FIN)", 
          "FLEA", "FLY (INSECT)", "FROG", "FUR", "GRASSHOPPER", "HORNS", "LIZARD", "MAGGOT", 
          "MUZZLE", "PEST", "POUCH", "SNAIL", "SNAKE", "SPIDER", "STING", "TAIL", "TUSKS", "WINGS", 
          "WORM"],
      },
    ],
  },
  {
    id: 'A23',
    category: 'A',
    categoryName: 'Everyday Scenes',
    title: 'Police / Law / Disputes',
    icon: '⚖️',
    wordCount: 72,
    subScenarios: [
      {
        id: 'A23-1',
        name: 'Crime / Public Security',
        wordCount: 35,
        words: ["ABUSE", "ALARM (SIREN)", "ARGUMENT", "ARREST", "ATTACK", "BULLY", "CANING", 
          "CAPTURE", "CONFLICT", "CRIMINAL", "FINGERPRINT", "FIRE", "GUARD", "GUILLOTINE", 
          "HANGING", "HOLD-UP", "JAIL", "KILL", "OFFENCE", "PEEPING TOM", "POLICE", "PUNCH", 
          "PUNISHMENT", "PUT OUT (EXTINGUISH)", "RAPE", "SEXUAL HARASSMENT", "SLAY", "STAB", 
          "STEALING", "STRANGULATION", "SUSPECT", "THIEF", "THRASH", "THREATENING", "WHIP (HIT)"],
      },
      {
        id: 'A23-2',
        name: 'Law / Judiciary',
        wordCount: 16,
        words: ["ADVOCACY", "ADVOCATE", "AMENDMENTS", "BAN", "COPYRIGHT", "COURT (LAW)", 
          "DISCRIMINATION", "EVIDENCE", "JUDGE", "LAW", "LEGAL", "OATH", "OBJECTION", "PETITION", 
          "RIGHT (LEGAL)", "SUMMONS"],
      },
      {
        id: 'A23-3',
        name: 'Politics / Military / Weapons',
        wordCount: 21,
        words: ["ARTILLERY", "BULLET", "CARTRIDGE", "COMMUNISM", "DEMOCRACY", "FEMINIST", 
          "GOVERNMENT", "GUN", "GUNFIRE", "MACHINE GUN", "MONARCH", "PLACARD", "POLITICS", 
          "PRINCE", "PRINCESS", "REVOLT", "RIFLE", "SPEAR", "SWORD", "VOTE"],
      },
    ],
  },
  {
    id: 'A24',
    category: 'A',
    categoryName: 'Everyday Scenes',
    title: 'Epidemic Protection',
    icon: '😷',
    wordCount: 6,
    subScenarios: [
      {
        id: 'A24-1',
        name: 'Epidemic Protection',
        wordCount: 6,
        words: ["COVID-19", "FACE MASK", "HOME ISOLATION", "LOCKDOWN", "MASK", "SOCIAL DISTANCING"],
      },
    ],
  },
  {
    id: 'A25',
    category: 'A',
    categoryName: 'Everyday Scenes',
    title: 'Deaf Culture / Sign Language',
    icon: '🤟',
    wordCount: 89,
    subScenarios: [
      {
        id: 'A25-1',
        name: 'Sign Linguistics',
        wordCount: 33,
        words: ["AUSLAN", "BEGINNING DIRECTIONAL", "CLASSIFIER", "CROSS-STICKS", "DIRECTIONAL", 
          "E OR E (FINGERSPELLING)", "END DIRECTIONAL", "EXPRESSION (FACIAL)", "EXPRESSIVENESS", 
          "FINGERSPELLING", "GESTURE", "GET ATTENTION", "HANDSHAPE", "ICONIC", "ICONICITY", 
          "INTERPRETATION", "LANGUAGE", "LINGUIST", "LOCATION (IN SIGNING SPACE)", "MIME", 
          "MORPHOLOGY", "MOUTH GESTURE", "MOVEMENTS", "PERSON MOVES", "PHONOLOGY", "PRONUNCIATION", 
          "SIGN BADLY", "SIGN LANGUAGE", "SIGN-NAME", "STRESS (EMPHASIS)", "SYNTAX", "TRANSCRIBE", 
          "TRANSLATION"],
      },
      {
        id: 'A25-2',
        name: 'Deaf Identity / Community',
        wordCount: 15,
        words: ["AUDITORY-VERBAL", "BRAILLE", "CUED-SPEECH", "DEAF CLUB", "DEAF MUTE", 
          "DUMB (MUTE)", "GALLAUDET UNIVERSITY", "HEARING IMPAIRED", "LIP READING", 
          "PROFOUNDLY DEAF", "USHER'S SYNDROME", "VOICE", "VOICELESS", "WAARDENBURG-SYNDROME", "WFD"],
      },
      {
        id: 'A25-3',
        name: 'Hearing / Assistive Devices',
        wordCount: 17,
        words: ["ALARM (FLASHING)", "ALARM CLOCK (VIBRATING)", "CAPTION", "COCHLEAR", "DEAFEN", 
          "DOORBELL (FLASHING LIGHT)", "FM HEARING AID", "HEARING", "HEARING LOOP", "HEARING LOSS", 
          "HEARING-AID", "LISTEN", "SOUND", "TELEBRAILLER", "TINNITUS", "TTY", "VIBRATION"],
      },
      {
        id: 'A25-4',
        name: 'Fingerspelling Alphabet',
        wordCount: 24,
        words: ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "P", "R", 
          "S", "T", "U", "V", "W", "X", "Y", "Z"],
      },
    ],
  },
  {
    id: 'A26',
    category: 'A',
    categoryName: 'Everyday Scenes',
    title: 'Body Parts',
    icon: '👁️',
    wordCount: 79,
    subScenarios: [
      {
        id: 'A26-1',
        name: 'Head & Face',
        wordCount: 23,
        words: ["BLINK", "CHEEK", "CHIN", "EAR", "EYE", "EYEBALL", "EYEBROWS", "EYELASHES", 
          "FOREHEAD", "FRECKLES", "HEAD", "JAWS", "LIP", "MOUTH", "NECK", "NOSE", 
          "NOSE (BIG NOSE)", "SALIVA", "SPIT", "TEETH", "TONGUE", "TONSILS", "TOOTH"],
      },
      {
        id: 'A26-2',
        name: 'Torso / Limbs',
        wordCount: 35,
        words: ["ABDOMEN", "ARM", "BACK (OF BODY)", "BODY", "BODY PARTS (POINTING TO)", "BONE", 
          "BOOBS", "BREAST", "BUM", "BUSTY", "BUTTOCKS", "CHEST", "ELBOW", "FIGURE (BODY SHAPE)", 
          "FINGER", "FINGERNAIL", "FOOT", "HAND", "HANDS", "HIP", "LEFT HANDED", "LEG", "MUSCLE", 
          "MUSCULAR", "RIGHT ARM", "RIGHT HANDED", "SHOULDER", "SKELETON", "SKINNINESS", "SKINNY", 
          "SLIM", "THUMB", "TOES", "WAIST", "WRIST"],
      },
      {
        id: 'A26-3',
        name: 'Internal Organs / Physiological Phenomena',
        wordCount: 21,
        words: ["ANUS", "BLOOD", "BOWEL", "BRAIN", "BREATH", "BREATHING", "FART", "FORESKIN", 
          "GOOSE PIMPLES", "GUT", "HEARTBEAT", "NERVE", "PENIS", "PISS", "POO", "SWEAT", 
          "TESTICLES", "URINATE", "UTERUS", "VAGINA", "WOMB"],
      },
    ],
  },
  {
    id: 'A27',
    category: 'A',
    categoryName: 'Everyday Scenes',
    title: 'Tools / Repair / DIY',
    icon: '🔧',
    wordCount: 50,
    subScenarios: [
      {
        id: 'A27-1',
        name: 'Hand Tools',
        wordCount: 23,
        words: ["BALL OF STRING", "CHAIN", "CHISEL", "CLIP", "DRILL", "HAMMER", "KNOT", "LADDER", 
          "PIN", "PLIERS", "PULLEY", "PUMP", "ROPE", "SAW (CUT)", "SCISSORS", "SCREWDRIVER", 
          "SHOVEL", "SPANNER", "SPIRIT LEVEL", "SPRAY GUN", "TAPE MEASURE", "TORCH", "WHEELBARROW"],
      },
      {
        id: 'A27-2',
        name: 'Construction / Materials',
        wordCount: 16,
        words: ["BRICK", "BUILD", "BULLDOZER", "CLAY", "CRANE", "DEMOLITION", "ENGRAVING", 
          "FOUNDATION", "FOUNDATIONS", "PAINT", "PLANE (SHAVE)", "PUTTY", "REPAIR", "REPAIRS", 
          "STUMPS (PYLONS)", "TAPE (ADHESIVE)"],
      },
      {
        id: 'A27-3',
        name: 'Sewing / Crafts',
        wordCount: 11,
        words: ["CABLE STITCH", "CROCHET", "KNITTING", "NEEDLE", "PURL (STITCH)", "REEL", "SEWING", 
          "SEWING MACHINE", "SPOOL", "STITCH", "WEAVE"],
      },
    ],
  },
  {
    id: 'B01',
    category: 'B',
    categoryName: 'Specialised Domains',
    title: 'Mathematics',
    icon: '📐',
    wordCount: 94,
    subScenarios: [
      {
        id: 'B01-1',
        name: 'Arithmetic / Algebra',
        wordCount: 49,
        words: ["ABSOLUTE VALUE", "ADDITION", "ALGEBRA", "APPROXIMATION", "ARITHMETIC", "AVERAGE", 
          "BINOMIAL", "CALCULATION", "CALCULATOR", "CONJUGATE (MATHEMATICS)", 
          "CONSTANT (MATHEMATICS)", "CUBE (MATHEMATICS)", "CUBE ROOT (MATHEMATICS)", "DENOMINATOR", 
          "DIVISION (MATHEMATICS)", "EQUAL (MATHEMATICS)", "EQUATION", "EXPONENT (MATHEMATICS)", 
          "FACTOR (MATHEMATICS)", "FACTORIAL", "FIFTH (FRACTION)", "FORMULA", "FRACTION", 
          "INFINITY", "INTEGRAL (SYMBOL)", "MAGNITUDE (MATHEMATICS)", "MATHEMATICS", "MAXIMUM", 
          "MINIMUM", "MINUS", "MONOMIAL", "MULTIPLICATION", "NUMERATOR", "PER CENT", "POLYNOMIAL", 
          "POWER OF (MATHEMATICS)", "PROPORTION", "RATIO", "RECIPROCAL (MATHEMATICS)", 
          "ROOT (MATHEMATICS)", "SQUARE (MATHEMATICS)", "SQUARE ROOT", "SUBTRACTION", 
          "THEREFORE (SYMBOL)", "THIRD (FRACTION)", "TOTAL", "TRINOMIAL", "VALUE (MATHEMATICS)", 
          "X (VALUE OF _X_)"],
      },
      {
        id: 'B01-2',
        name: 'Geometry / Shapes',
        wordCount: 28,
        words: ["ANGLE", "AREA (SURFACE AREA)", "AXIS", "BASE (OF TRIANGLE)", "BLOCK (SHAPE)", 
          "CIRCLE", "CIRCUMFERENCE", "CO-ORDINATE", "CURVE", "CYLINDER", "DEPTH", "DIAGONAL", 
          "DIAMETER", "GEOMETRY", "HORIZONTAL", "HYPOTENUSE", "ORIGIN (MATHEMATICS)", "OVAL", 
          "PARALLEL", "PERIMETER", "PYRAMID", "RADIUS", "RECTANGLE", "RIGHT ANGLE", "SQUARE", 
          "SYMMETRICAL", "TRIANGLE", "VERTICAL"],
      },
      {
        id: 'B01-3',
        name: 'Functions / Analysis / Statistics',
        wordCount: 17,
        words: ["ALPHA", "ASYMPTOTE", "BETA", "CALCULUS", "DIVERGENCE", "FUNCTION (MATHEMATICS)", 
          "GAMMA", "GRAPH", "OMEGA", "PARABOLA", "POINT (DOT)", "SECANT", "SIGMA", "STATISTICS", 
          "TANGENT", "THETA", "TRIGONOMETRY"],
      },
    ],
  },
  {
    id: 'B02',
    category: 'B',
    categoryName: 'Specialised Domains',
    title: 'Religion',
    icon: '🙏',
    wordCount: 67,
    subScenarios: [
      {
        id: 'B02-1',
        name: 'Deities / Faith Concepts',
        wordCount: 22,
        words: ["ADHERENT", "ASCENSION", "CONVERT", "CREATION", "DELIVERANCE", "DEVIL", 
          "ENLIGHTENMENT", "EXALTATION", "FAITH", "GLORY", "GOD", "HEAVEN", "HOLY SPIRIT", "JESUS", 
          "LORD", "MESSIAH", "PROPHECY", "REPENT", "SAINTLY", "SALVATION", "SPIRIT", "TRINITY"],
      },
      {
        id: 'B02-2',
        name: 'Church / Denominations / Clergy',
        wordCount: 20,
        words: ["ALTAR", "BISHOP", "CATHOLICISM", "CENTURION", "CHURCH", "CONGREGATE", "JEW", 
          "LUTHERAN", "MINISTER", "MISSIONARY", "MORMON", "NUN", "ORDINATION", "PASTOR", 
          "PENTECOSTALISM", "PHARISEE", "POPE", "PREACHER", "PRIEST", "PROTESTANT"],
      },
      {
        id: 'B02-3',
        name: 'Ceremonies / Scriptures / Festivals',
        wordCount: 25,
        words: ["ADVENT", "AMEN", "BAPTISE", "BAPTISED", "BAPTISM", "BIBLE", "BLESS", "BLESSING", 
          "CALVARY", "COMMANDMENT", "CONFESSION", "CRUCIFIXION", "EASTER", "EPISTLE", "GOSPEL", 
          "HALLELUJAH", "HOLY COMMUNION", "LITURGY", "NAZARETH", "PRAYER", "ROSARY", "TESTAMENT", 
          "VERSE", "WORSHIP", "ZION"],
      },
    ],
  },
  {
    id: 'B03',
    category: 'B',
    categoryName: 'Specialised Domains',
    title: 'Sport-Specific Terminology',
    icon: '🏆',
    wordCount: 39,
    subScenarios: [
      {
        id: 'B03-1',
        name: 'Cricket',
        wordCount: 13,
        words: ["ALL OUT", "BOUNDARY", "BOWLED OUT (CRICKET)", "BOWLER (CRICKET)", 
          "DECLARE (CRICKET)", "MAIDEN (CRICKET)", "OVER (CRICKET)", "RUNS", 
          "SILLY MID ON (CRICKET)", "STUMP (CRICKET)", "WICKET", "WICKET-KEEPER"],
      },
      {
        id: 'B03-2',
        name: 'Australian Rules Football',
        wordCount: 12,
        words: ["AUSTRALIAN RULES", "BALL-UP (AUSTRALIAN RULES FOOTBALL)", "BARRACKER", 
          "BOUNDARY UMPIRE", "CENTRE HALF-BACK", "CENTRE HALF-FORWARD", "FULL-BACK", 
          "FULL-FORWARD", "GOAL (AFL)", "GOAL UMPIRE", "ROVER", "RUCK"],
      },
      {
        id: 'B03-3',
        name: 'Rugby / Other',
        wordCount: 14,
        words: ["ADVANTAGE (TENNIS)", "AIM (ARROW)", "BREAKAWAY (RUGBY)", "DEUCE (TENNIS)", 
          "FIVE-EIGHTH (RUGBY)", "FORWARD (RUGBY)", "GOAL (BASKETBALL)", "HALF-TIME", "HOOKER", 
          "LINE-UMPIRE", "LOCK (RUGBY)", "SCRUM", "SECOND ROWER", "SWISH (BASKETBALL)"],
      },
    ],
  },
  {
    id: 'B04',
    category: 'B',
    categoryName: 'Specialised Domains',
    title: 'Cars / Machinery',
    icon: '⚙️',
    wordCount: 46,
    subScenarios: [
      {
        id: 'B04-1',
        name: 'Engine / Power',
        wordCount: 19,
        words: ["ACCELERATOR", "CARBURETTOR", "CHOKE (CAR)", "ENGINE", "FAN BELT", 
          "FOUR-CYLINDER ENGINE", "GASOLINE", "GEARS", "MOTOR", "PETROL FILTER", "PISTON", 
          "PISTON RING", "POINTS (SPARK PLUGS)", "RADIATOR (ENGINE)", "RUN (ENGINE)", 
          "SIX-CYLINDER", "THROTTLE", "TRAVERSE ENGINE", "V8 ENGINE"],
      },
      {
        id: 'B04-2',
        name: 'Bodywork / Components',
        wordCount: 15,
        words: ["BALD TYRE", "BOOT (CAR)", "EXHAUST PIPE", "GRILLE (GUARD)", "HEADLIGHTS", "HOOD", 
          "HORN (CAR)", "INDICATORS", "POWER WINDOWS", "SUNROOF", "TOW BAR", "TYRE", "WHEEL", 
          "WINDSCREEN WASHERS", "WINDSCREEN WIPERS"],
      },
      {
        id: 'B04-3',
        name: 'Handling / Repair',
        wordCount: 12,
        words: ["BRAKE", "BREAKDOWN", "GAUGE", "GREASE", "GREASE GUN", "JACK", "JUMPER LEADS", 
          "MANUAL CAR", "PANEL BEATER", "PUNCTURE", "REBORE", "WHEEL ALIGNMENT"],
      },
    ],
  },
  {
    id: 'B05',
    category: 'B',
    categoryName: 'Specialised Domains',
    title: 'Countries / Place Names',
    icon: '🌍',
    wordCount: 67,
    subScenarios: [
      {
        id: 'B05-1',
        name: 'Countries / Regions',
        wordCount: 36,
        words: ["AFRICA", "AMERICA (USA)", "AMERICAS (NORTH AND SOUTH AMERICA)", "ASIA", 
          "AUSTRALIA", "AUSTRIA", "BRITAIN", "CANADA", "CHILE", "DENMARK", "EGYPT", 
          "EGYPT (ANCIENT EGYPT)", "ENGLAND", "EUROPE", "FRANCE", "GREECE", "HONG KONG", "ICELAND", 
          "INDIA", "INDONESIA", "IRELAND", "ITALY", "JAPAN", "KOREA", "MALAYSIA", "MEXICO", 
          "NETHERLANDS", "NEW ZEALAND", "NORWAY", "PHILIPPINES", "RUSSIA", "SINGAPORE", 
          "SWITZERLAND", "THAILAND", "VIETNAM", "WALES"],
      },
      {
        id: 'B05-2',
        name: 'Cities',
        wordCount: 16,
        words: ["ADELAIDE", "AMSTERDAM", "BERLIN", "BRISBANE", "CAIRNS", "CANBERRA", "DUBLIN", 
          "HOBART", "LOS ANGELES", "MONTREAL", "NEW YORK", "NEWTOWN", "PARRAMATTA", "PERTH", 
          "SYDNEY", "TOKYO"],
      },
      {
        id: 'B05-3',
        name: 'Ethnic Groups / General Geographic Terms',
        wordCount: 15,
        words: ["ABORIGINE", "AMERINDIAN", "BLACK (PERSON)", "BORDER", "COUNTRY", "COUNTRY-WIDE", 
          "ETHNIC", "FLAG", "INDIGENOUS", "INTERNATIONAL", "MAORI", "MELBURNIAN", "REGION", 
          "SPANIARD", "WORLD"],
      },
    ],
  },
  {
    id: 'C01',
    category: 'C',
    categoryName: 'Grammar Words / Abstract Concepts',
    title: 'Grammar / Function Words / Pronouns',
    icon: '📖',
    wordCount: 151,
    subScenarios: [
      {
        id: 'C01-1',
        name: 'Pronouns',
        wordCount: 32,
        words: ["EACH OTHER", "EVERYONE", "EVERYTHING", "HERE", "HERE (PLURAL)", "IT", "ITS", 
          "ITSELF", "ME", "MY", "MY (NOT MY)", "MYSELF", "NO ONE", "NOTHING", "OUR", "OURSELVES", 
          "SELF (PREFIX)", "SOME", "THEIR", "THEY", "THING", "THOU", "THY", "WE", "WHO", "YOU", 
          "YOU (PLURAL)", "YOUR", "YOUR (NOT YOUR)", "YOUR (PLURAL)", "YOURSELF", "YOURSELVES"],
      },
      {
        id: 'C01-2',
        name: 'Direction / Deixis',
        wordCount: 48,
        words: ["ABOVE", "ACROSS", "AHEAD", "AROUND", "BACK", "BACKWARD", "BEHIND", "BENEATH", 
          "BESIDE", "COMING", "DOWN", "DOWNWARD", "EAST", "FACING", "FAR", "FORWARD", "FRONT", 
          "GO", "GO ACROSS", "GO AHEAD", "GO TO", "GO WITH", "GONE", "IN", "INSIDE", "LEFT SIDE", 
          "LEFTWARDS", "MIDDLE", "NEAR", "NEXT", "NORTH", "OFF", "ON", "OPPOSITE", "OUT", 
          "OUTSIDE", "OVER", "RIGHTWARDS", "SIDE", "SIDEWARD", "SOUTH", "STOP", "TO", "TOWARD", 
          "UNDERSIDE", "UPWARD", "WEST", "WHEREABOUTS"],
      },
      {
        id: 'C01-3',
        name: 'Conjunctions / Auxiliary Verbs / Question Words',
        wordCount: 71,
        words: ["AGAIN", "AGAINST", "ALL", "ALL TOGETHER", "ALMOST", "ALREADY", "ALSO", "AND", 
          "ARE", "BE (NOT BE)", "BECOME", "BIT", "BOTH", "BUT", "COMPLETELY", "CONCERNING", "DID", 
          "DO", "DO (DO NOT)", "DOES", "DON'T KNOW", "EACH", "ENOUGH (NOT ENOUGH)", "ET CETERA", 
          "EVERY", "EXCEPTION", "FEW", "FINALLY", "HAVE", "IF", "IN CASE", "KIND (SORT)", "LASTLY", 
          "LIKE", "MAY", "MORE", "MOREOVER", "MUST", "NEITHER", "NEVER", "NO", "NOT", "OFTEN", 
          "ONE MORE", "ONLY", "OR", "OTHERWISE", "RATHER", "SAME", "SHOULD", "SHOULD (SHOULD NOT)", 
          "SINCE", "SO", "THAN", "THAT'S ALL", "THEN", "THREE MORE", "TOO MANY", "TWO MORE", 
          "UNTIL", "WHAT", "WHATEVER", "WHEN", "WHETHER", "WHY", "WHY-NOT", "WILL", "WITH", 
          "WITHOUT", "WON'T", "YET (NOT YET)"],
      },
    ],
  },
  {
    id: 'C02',
    category: 'C',
    categoryName: 'Grammar Words / Abstract Concepts',
    title: 'Abstract Concepts / Properties / Actions',
    icon: '💡',
    wordCount: 628,
    subScenarios: [
      {
        id: 'C02-1',
        name: 'Properties / States / Degree',
        wordCount: 208,
        words: ["ABLE", "ABSENCE", "AGAPE", "ALERTNESS", "ALONE", "APPEARANCE", "AQUARIUS", 
          "ARBITRARINESS", "ARROW", "AUTOMATIC", "AVAILABILITY", "BACKGROUND", "BARRIER", "BASE", 
          "BEHAVIOUR", "BIG", "BLANK", "BLOCKAGE", "BLUNT", "BLUR", "BREVITY", 
          "BRICK WALL (OBSTACLE)", "BRIGHTNESS", "BUFFER", "BUNDLE", "BURDEN", "CAPACITY", 
          "CENTRE", "CLEANNESS", "CLEAR", "CLOSE SHAVE", "COARSE", "COLUMN", "COMFORTABLE", 
          "COMPLICATION", "COMPONENT", "CONTINUUM", "CONTRACTED", "CONTRACTION (SHRINKAGE)", 
          "CONVENIENT", "CORNER", "CRACK", "CROWN", "CRYSTAL", "CURRENT", "DEVELOPED", 
          "DIFFICULTY", "DRYNESS", "DULLNESS", "EASE", "EASY-PEASY", "ELAN", "EMPTY", 
          "ENLARGEMENT", "EQUIPMENT", "EXACT", "EXACTITUDE", "EXAMPLE", "EXPRESS (VERY FAST)", 
          "EXTENSION", "FAST", "FAT", "FILLER", "FINAL", "FLAT SURFACE (HIGH)", "FOAM", "FREE", 
          "GADABOUT", "GENERAL", "GENIE", "GHOST", "GLOBALISATION", "GOLD", "GREEN", "GREY", 
          "GROUP", "GROWTH", "HABIT", "HAPPENING", "HARDNESS", "HEAP", "HEAVY", "HOLE", "HUGE", 
          "HUMAN", "IDLENESS", "IMPOSSIBLE", "IMPROBABLE", "INDEPENDENCE", "INDIRECT", 
          "INDIVIDUAL", "ISOLATED", "ISSUE", "LIFE", "LIGHTWEIGHT", "LIMIT", "LINE", "LINES", 
          "LITTLE", "LOOSE", "LOSS", "LOUD", "LOWNESS", "MAJORITY", "MANNERISM", 
          "MATTER (PROBLEM)", "MESS", "MINOR", "MISSING", "MODEL", "MONOTONY", "NARROW", "NATURAL", 
          "NEW", "NORMALITY", "NOTHING HAPPEN", "NOVELTY", "OBSCURITY", "OBVIOUS", "ODOUR", 
          "OLD-FASHIONED", "ONGOING", "OPAQUE", "ORIENTATION", "ORIGINAL", "PART", "PEACE", 
          "PEACEFUL", "PEOPLE", "PERMANENCE", "PERSON", "PERSON (AT)", "PILE", "PIRATE", 
          "PLAINNESS", "PLASTIC", "PONG", "POSSIBILITY", "POWER", "PRESSURE", "PRIVACY", "PROFILE", 
          "PROTECTOR", "QUICK", "QUIETLY", "REDUCTION", "REGULARITY", "REMAINS", "REPETITIVE", 
          "RESOURCES", "ROUGH", "ROUGHNESS", "RUBBER (MATERIAL)", "RULES", "SAGITTARIUS", "SECRET", 
          "SELECTION", "SEQUENCE", "SERIES", "SHALLOW", "SHARP", "SHIELD", "SHRINKAGE", "SILENCE", 
          "SIMPLICITY", "SITE", "SITUATION", "SLOWNESS", "SMALL", "SMOOTH", "SOCIETY", "SOLID", 
          "SORT", "SPASMODIC", "SPELL (MAGIC)", "STICKY", "STIFF", "STRAIGHT", "STRANGE", 
          "STRATIFICATION", "STRONG", "STRUCTURE", "SUFFICIENCY", "SURVIVORS", "SYMBOL", "SYSTEM", 
          "TABULA RASA", "TALL", "TIER", "TIGHTNESS", "TIP (END POINT)", "TRANSIENT", 
          "TRANSPARENT", "TROUBLE", "TUBE", "UFO", "UNDETECTABLE", "UNIFORMITY", "UNIQUE", 
          "UNUSUAL", "VAMPIRE", "VARIATION", "WAND", "WEAKLING", "WEIRD", "WETNESS", "WILD", "WITCH"],
      },
      {
        id: 'C02-2',
        name: 'Cognition / Thinking',
        wordCount: 72,
        words: ["ACCEPTANCE", "ADMISSION", "ADMIT", "AIM", "ATTENTION", "BELIEVE (NOT BELIEVE)", 
          "BELIEVE IN", "CATCH (UNDERSTAND)", "CHANGE MIND", "CHOOSE", "COGITATION", 
          "COME UP WITH", "COMMON KNOWLEDGE", "CONCENTRATION", "CONFIRM", "CONSIDERATION", 
          "CONTEMPLATE", "DECIDE", "DECISION", "DENIAL", "DENY", "DISCOVER", "DISREGARD", 
          "DISTRACTION", "ENVISAGE", "EVALUATE", "EXAMINE", "EXAMINED", "EXPECT", "FAMILIAR", 
          "FAMILIARITY", "FOCUS", "FORGET", "FORGET (GO BLANK)", "FORGETFULNESS", "FOUND OUT", 
          "GO BLANK (FORGET)", "IDEA (GET IDEA)", "IGNORANCE", "IMPRESSION", "INDECISION", 
          "INDECISIVE", "INFORMED", "INTUITION", "KNOW (NOT KNOW)", 
          "KNOW FINISH (BEEN THERE DONE THAT)", "KNOW WELL", "KNOWLEDGE", "LOGIC", "MEANING", 
          "MIND", "MIND (NOT MIND)", "MISINTERPRET", "MULL OVER", "OBLIVIOUS", "OBSERVATION", 
          "OBSERVE", "OVERLOOK", "PERSPECTIVE", "REALISATION", "REALISE", "RECOGNITION", 
          "RECOLLECT", "REMINDER", "STRATEGY", "SUPPOSE", "THINK", "THINKING (REFLECTION)", 
          "TOUCH FINISH (BEEN-THERE-DONE-THAT)", "VIEW", "WANT (NOT WANT)", "WISH"],
      },
      {
        id: 'C02-3',
        name: 'General Actions / Operations',
        wordCount: 252,
        words: ["ABOUT-TURN", "ABSCOND", "ACCESS", "ACCUMULATION", "ACQUIRE", "ACTION", "ACTIVITY", 
          "ADAPT", "ADVANCE", "ANNOUNCE", "ANSWER", "APPLY", "APPROACH", "ARRANGE", "ATTAIN", 
          "ATTEMPT", "AVOID", "AVOIDANCE", "BEG", "BEND", "BLOW UP", "BORE", "BOTHER", 
          "BOTHER (NO BOTHER)", "BOUNCE", "BOW (BEND OVER)", "BREAK", "BRING FORWARD", "BUILD UP", 
          "BURST INTO FLAMES", "CADGE", "CARRY", "CARRY OFF", "CARRY ON TO", "CHALLENGE", "CHASE", 
          "CLOSE", "CLOSURE", "COERCION", "COLLAPSE", "COLLECT", "COMPLETE (FINISH)", "CONCEAL", 
          "CONTINUATION", "CONTRIBUTION", "CONTROL", "COPY", "COVER", "COVER UP", "CRUSH", "CUT", 
          "CUT OUT", "DAMAGE", "DEMAND", "DEPLETE", "DESCRIBE", "DETERIORATE", "DIGRESSION", 
          "DISALLOW", "DISAPPEAR (INTO DISTANCE)", "DISSIMULATE", "DISTURB", "DROP", 
          "DUCK (LOWER HEAD)", "DUMP", "ELIMINATE", "EMIT", "EMPOWER", "ENDING", "ENLARGE", 
          "ENTICE", "ERR", "EXTRACT", "FALL (TOPPLE)", "FALL BACK", "FILL UP", "FILTER", "FIND", 
          "FINISH", "FLASH", "FLICKER", "FLOUNDERING", "FLOW", "FLUTTER", "FOLD", "FORSAKE", 
          "GAZE", "GET OUT", "GET RID OF", "GIVE", "GIVE IN", "GRAB", "HAND OVER", "HIDE OUT", 
          "HIT", "HOLD", "HOP", "HURRY", "IMPACT", "IMPROVISATION", "INCREASE", "INDULGENCE", 
          "INFLUENCE", "INTERFERENCE", "JUMP OFF", "KABOOM", "KEEPING", "KNEEL", "LAUNCH", "LIFT", 
          "LIGHT UP", "LIGHTEN", "LOOK", "LOOK BACK", "LOWER (FLAG)", "MAKING", "MARCH", "MISS", 
          "MISS OUT", "MOVE", "MOVE AHEAD", "MOVING ON", "NEED", "NUDGE", "OBEY", "OBLIGED", 
          "OFFER", "OFFLOAD", "OPEN", "ORDER (COMMAND)", "ORDERED", "ORIENTATING", "OVERFLOW", 
          "OVERTURN", "PARTICIPATE", "PARTICIPATION", "PASS", "PAT", "PEEK", "PERMISSION", 
          "PERSUASION", "PICK UP", "PINCH", "PLEADING", "PLEASE ONESELF", "POINT", "POKE", 
          "POTTER ABOUT", "PREPARATION", "PRESENT (HAND OVER)", "PRESS", "PREVENTION", "PROGRESS", 
          "PROVISION", "PULL", "PULL APART", "PUSH", "PUSH DOWN", "PUT", "PUT AWAY", "RAISE", 
          "RAISE (FLAG)", "RECEIVE", "RECOMMEND", "REFER", "REFUSAL", "REMAIN", "REMOVAL", 
          "REMOVE", "REPLACE", "REPRESSION", "RESISTANCE", "RESTRAINT", "RESTRICTION", "RETURN", 
          "RID", "ROLL", "RUB", "RUBBING", "SAFEKEEPING", "SCORE (SCRATCH)", "SCRAPE", "SCRATCH", 
          "SEARCH", "SEE", "SEEN", "SEPARATE", "SHAKE", "SHARE", "SHINE (REFLECT)", "SHOW UP", 
          "SHUT", "SINKING", "SIT", "SIT (AT)", "SIT (OPPOSITE EACH OTHER)", "SKIM", "SLIP", 
          "SPILL", "SPINNING", "SPLASH", "SPOIL", "SPRAY", "SPREAD", "SPURT", "SQUASH (CRUSH)", 
          "SQUEEZE", "STACK", "STAND", "START", "STASH", "STAY", "STEP", "STICK", "STRAIGHTEN", 
          "STRIDE", "STRIP", "STRIVE", "SUBMISSION", "SUGGEST", "SUGGESTION", "SURGE", "SURRENDER", 
          "SURROUND", "SUSPEND", "SWAP", "SWITCH (CHANGEOVER)", "TAKE", "TAP", "TEAR (RIP)", 
          "THROW", "THROW (UPWARDS)", "THROW OUT", "TICK", "TILT", "TIPTOE", "TOPPLE OVER", 
          "TOUCH", "TRANSFER", "TRICK", "TRIP (FALL)", "TURN OVER", "TWIDDLE THUMBS", "TWIST", 
          "UNFOLD", "USE", "VANISH (INTO DISTANCE)", "WARNING", "WASTE", "WIDEN", "WIND UP", 
          "WORSEN"],
      },
      {
        id: 'C02-4',
        name: 'Relationships / Logic / Comparison',
        wordCount: 25,
        words: ["ACCORD", "AGREEMENT", "ALTERNATE", "CLOSENESS", "COINCIDENCE", "COMPARISON", 
          "CONNECTION", "DEPEND ON", "DIFFERENCE", "DIFFERENCES", "DISAGREEMENT", "EQUALIZE", 
          "FIT", "FIT INTO", "INTEGRATION", "INVOLVE", "JOIN", "LOOK LIKE", "PAIR", "PAIR UP", 
          "PAIRS", "RELEVANCE", "SAMENESS", "SIMILARITY", "SUIT (SUIT SOMEONE)"],
      },
      {
        id: 'C02-5',
        name: 'Evaluation / Value Judgments',
        wordCount: 71,
        words: ["ABOMINATION", "ADVANTAGE", "ADVANTAGED", "BAD", "BAD LUCK", "BEAUTIFUL", "BEAUTY", 
          "BENEFIT", "BEST", "BETTER", "BIASED", "BRAINY", "BRIGHT (SMART)", "BRILLIANT", "CLEVER", 
          "CLEVER (NOT CLEVER)", "CUTE", "DECENCY", "DECEPTION", "DISADVANTAGE", "EXAGGERATION", 
          "EXCELLENCE", "EXQUISITE", "FAILURE", "FAIR", "FAIRNESS", "FAULT", "GENIUS", "GENUINE", 
          "GO WELL", "GOOD (NO GOOD)", "GOODNESS", "HANDSOME", "IMPORTANCE", "IMPROVEMENT", 
          "INNOCENCE", "INNOCENT (INEXPERIENCED)", "LOUSINESS", "LOUSY", "LUCK", 
          "MATTER (NOT MATTER)", "NECESSITY", "NEGATIVE", "NICE", "OPPORTUNITY", "OUTSTANDING", 
          "PERFECTION", "POPULAR", "PRETENCE", "PRETTINESS", "PROPER", "PURITY", "REAL", 
          "RESPONSIBILITY", "RESPONSIBLE (NOT RESPONSIBLE)", "RIDICULOUS", "RISK", "SKILL", 
          "SKILLED", "STAND OUT", "SUCCESS", "TALENT", "TERRIBLE", "TROUBLE-FREE", "TRUTHFULLY", 
          "UGLINESS", "USELESS", "WELL-KNOWN (FAMOUS)", "WISDOM", "WORSE", "WRONG"],
      },
    ],
  },
];

export const SCENARIO_STATS = {
  totalCategories: SCENARIO_CATEGORIES.length,
  A: { name: 'Everyday Scenes', count: SCENARIO_CATEGORIES.filter(g => g.category === 'A').length },
  B: { name: 'Specialised Domains', count: SCENARIO_CATEGORIES.filter(g => g.category === 'B').length },
  C: { name: 'Grammar Words / Abstract Concepts', count: SCENARIO_CATEGORIES.filter(g => g.category === 'C').length },
};

export function getScenarioById(id: string): ScenarioGroup | undefined {
  return SCENARIO_CATEGORIES.find(group => group.id === id);
}

export function getSubScenarioById(id: string): SubScenario | undefined {
  for (const group of SCENARIO_CATEGORIES) {
    const sub = group.subScenarios.find(s => s.id === id);
    if (sub) return sub;
  }
  return undefined;
}